# This file configures `borg` to compare files to the Illinois Cybersecurity Development default template

[template]
files_url = "https://raw.githubusercontent.com/techservicesillinois/secdev-template-repository/refs/heads/main/"
files = [
    ".github/workflows/pr_reminder.yml",
    ".github/workflows/cleanup.yml",
    "CODE_OF_CONDUCT.md",
    "SECURITY.md",
]

##############################################################################
#
# Guidance on LICENSE.txt and COPYRIGHT.txt
#
# In COPYRIGHT.txt: 
#
# Assign Copyright to each primary contributor.
#
# Paid work for the University of Illinois should also assign Copyright to the
# University of Illinois Board of Trustees to allow the University to
# re-license the work.
#
# Example copyright text: 
#
# Copyright <year(s)> <primary contributor 1>, <primary contributor 2>,
# <primary contributor 3> and the University of Illinois Board of Trustees
# 
# In LICENSE.txt:
#
# A license that protects the University from liability should be inlcuded in 
# public source code.
#
# Strong copyleft licenses may be preferred on larger works to compel adopters
# to share updates and security patches they create.
#
# The University of Illinois Office of Technology Management
# can assist with novel licensing needs.
# 
##############################################################################

file_contents = [
  # Paid work should co-assign copyright to the Board of Trustees
	['COPYRIGHT.txt', 'and the University of Illinois Board of Trustees'],
	['LICENSE.txt', '"AS IS"'],  # A warrany disclaimer is required
	['README.md', '# About'],
  # Document Data Sources and Endpoints to comply with University IT security policy
  # https://answers.uillinois.edu/illinois/111571
	['README.md', '## Data Sources'],
	['README.md', '## Endpoint Connections'],
	['README.md', 'Support'],
  # README should describe support as 'best-effort'
	['README.md', 'on a best-effort basis'],
  # README should give an estimated date for end of support
	['README.md', 'End-of-Support'],

]

[generate.gitattributes]
files = [
    # All machine generated files
    ".gitattributes",
]
# Include all template files above
include_template_files = true
